### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by maximilian-walter** [dmitryd/typo3-sentry#1]
I suggest to use semantic versioning for this extension. In the TYPO3-backend it is currently not possible to see if the installed version is the most current one.

http://semver.org/

Thanks for your work!

**Comment by dmitryd** [comment]
I always use semantic versioning for all my extensions. What makes you think I don't?

**Comment by maximilian-walter** [comment]
Thanks for your fast reply. I downloaded this extension via GitHub and the version is "0.0.0":

https://github.com/dmitryd/typo3-sentry/blob/development/ext_emconf.php#L35

**Comment by dmitryd** [comment]
TYPO3 extension versions are increased when the extension is released (=a new version appears in TER). This extension was never sent to TER. You downloaded the current development version, which is 0.0.0. If you look into any other my extensions (like realurl or dd_googlesitemap), you will see that the patch version is for regular bug fixes, minor version if large updates and major version is rserved for incompatible updates. Same is here.

**Comment by maximilian-walter** [comment]
Thanks for clarification. Is there a reason to not upload this extension to TER? I find it very useful and use it with multiple TYPO3 installations.

**Comment by dmitryd** [comment]
I need to make more testing.

**Comment by dmitryd** [comment]
Release 1.0.0 is available now.
